# fly.toml app configuration file generated for falling-water-6948 on 2023-07-26T19:55:30+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "falling-water-6948"
primary_region = "nrt"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[env]
  MONGO_URI="mongodb+srv://ysoon0912:8zq1eZWvfSuzqm0r@cluster0.iapquck.mongodb.net/blog?retryWrites=true&w=majority"
  JWT_SECRET="cat"